name: "Deploy to Nuget"

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop

env:
  SOLUTION_PATH: './FmgLib.MauiMarkup.sln'
  PROJECT_PATH: 'src\FmgLib.MauiMarkup\FmgLib.MauiMarkup.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Clean output directory
      run: dotnet clean ${{ env.SOLUTION_PATH }} -c Release

    - name: Build the solution
      run: dotnet build ${{ env.SOLUTION_PATH }} -c Release

    # - name: 'Restore package'
    #   run: dotnet restore ${{ env.PROJECT_PATH }}

    # - name: 'Build project'
    #   run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
